name: Fly_Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
        - uses: actions/checkout@v4.1.6
        - run: corepack enable
        - uses: actions/setup-node@v4.0.2
          with:
            node-version: '20.11.1'
            cache: 'yarn'
            cache-dependency-path: './yarn.lock'
        - run: yarn install
        - run: yarn build
          working-directory: ./pkg/common/
        - run: yarn build:prod
          working-directory: ./pkg/gui
        - uses: superfly/flyctl-actions/setup-flyctl@1.5
        - run: flyctl deploy --remote-only
          env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}